/// The English source text for every translatable label in the dealer app.
///
/// This map is the fallback shown when a translation has not arrived yet, and
/// it is also what gets posted to `POST /translations/sync` so the server can
/// translate and store the strings. Keys are `group.name`; the group is what
/// the admin Website Translations screen filters on, so keep it meaningful.
const Map<String, String> kAppStringsEn = <String, String>{
  // --- account -----------------------------------------------------------------
  'account.assigned_salesman': 'Assigned Salesman',
  'account.dealer_code': 'Dealer Code',
  'account.email_optional': 'Email (optional)',
  'account.firm_name': 'Firm Name',
  'account.gst_number': 'GST Number (optional)',
  'account.gst_number_plain': 'GST Number',
  'account.owner_name': 'Owner / Contact Name',
  'account.profile_details': 'Profile Details',
  'account.profile_photo': 'Profile Photo',

  // --- address -----------------------------------------------------------------
  'address.add': 'Add Address',
  'address.add_delivery': 'Add a delivery address',
  'address.add_new': 'Add new address',
  'address.add_short': 'Add',
  'address.choose': 'Choose delivery address',
  'address.deliver_to_label': 'Deliver to {address}',
  'address.delivery_address': 'Delivery Address',
  'address.full_name': 'Full Name',
  'address.mobile': 'Mobile Number',
  'address.name': 'Name',
  'address.not_available': 'Address not available',
  'address.pincode': 'Pincode',
  'address.required': 'Address Required',
  'address.required_short': 'Enter name, mobile and address.',
  'address.save': 'Save Address',
  'address.save_failed': 'Save Failed',
  'address.saved_message': 'Delivery address has been saved.',
  'address.saved_title': 'Address Saved',
  'address.state': 'State',

  // --- auth --------------------------------------------------------------------
  'auth.already_registered': 'Already registered?',
  'auth.approval_note': 'Your account will be activated after admin approval.',
  'auth.approval_pending': 'Approval Pending',
  'auth.approval_pending_message': 'Your dealer account is waiting for admin approval.',
  'auth.confirm_new_password': 'Confirm New Password',
  'auth.current_password': 'Current Password',
  'auth.dealer_registration': 'Dealer Registration',
  'auth.email': 'Email',
  'auth.email_address': 'Email Address',
  'auth.email_required': 'Email Required',
  'auth.enter_contact_name': 'Enter owner / contact name (at least 3 characters).',
  'auth.enter_firm_name': 'Enter shop / firm name.',
  'auth.enter_mobile': 'Enter your mobile number',
  'auth.enter_mobile_again': 'Please go back and enter your mobile number again.',
  'auth.enter_otp_the': 'Enter the 6 digit OTP.',
  'auth.enter_password': 'Enter your password.',
  'auth.enter_valid_email': 'Enter a valid email address.',
  'auth.enter_valid_gst': 'Enter a valid 15 character GST number or leave it blank.',
  'auth.enter_valid_mobile_10': 'Enter a valid 10 digit mobile number.',
  'auth.firm_details': 'Firm Details',
  'auth.firm_name_required': 'Firm Name Required',
  'auth.firm_shop_name': 'Firm / Shop Name',
  'auth.hide_password': 'Hide password',
  'auth.invalid_email': 'Invalid Email',
  'auth.invalid_gst': 'Invalid GST Number',
  'auth.invalid_otp': 'Invalid OTP',
  'auth.login_failed': 'Login Failed',
  'auth.mobile': 'Mobile',
  'auth.mobile_missing': 'Mobile Missing',
  'auth.mobile_otp': 'Mobile OTP',
  'auth.mobile_required': 'Mobile Required',
  'auth.name_required': 'Name Required',
  'auth.new_dealer': 'New dealer?',
  'auth.new_password': 'New Password',
  'auth.number_privacy': 'Your number is used only for login and order updates.',
  'auth.otp_code_hint': 'Enter the 6 digit code we sent you',
  'auth.otp_failed': 'OTP Failed',
  'auth.otp_numbers_only': 'OTP must contain only numbers.',
  'auth.otp_required': 'OTP Required',
  'auth.otp_resent': 'A new OTP has been sent.',
  'auth.otp_sent': 'OTP Sent',
  'auth.otp_sent_to_mobile': 'OTP sent to +91 {mobile}',
  'auth.otp_subtitle': 'We will send a 6 digit OTP to your registered mobile number.',
  'auth.otp_verification_failed': 'OTP Verification Failed',
  'auth.otp_verify_it': 'We will send a 6 digit OTP to verify it.',
  'auth.password': 'Password',
  'auth.password_min': 'Password must be at least 6 characters.',
  'auth.password_required': 'Password Required',
  'auth.register_firm': 'Register your firm',
  'auth.register_subtitle': 'Register your firm in three quick steps',
  'auth.register_title': 'Tell us about your business',
  'auth.registration_complete': 'Your dealer registration is complete. You can log in once admin approves your account.',
  'auth.registration_failed': 'Registration Failed',
  'auth.registration_submitted': 'Registration Submitted',
  'auth.request_otp_again': 'Please request OTP again.',
  'auth.resend_otp': 'Resend OTP',
  'auth.send_otp': 'Send OTP',
  'auth.show_password': 'Show password',
  'auth.sign_in_subtitle': 'Sign in to your dealer account',
  'auth.submit_registration': 'Submit Registration',
  'auth.verification_required': 'Verification Required',
  'auth.verified_mobile': 'Verified mobile',
  'auth.verify_first': 'Please verify your mobile number first.',
  'auth.verify_mobile': 'Verify Mobile Number',
  'auth.verify_otp': 'Verify OTP',
  'auth.welcome_back': 'Welcome Back',

  // --- cart --------------------------------------------------------------------
  'cart.available_credit': 'Available credit',
  'cart.case_count_many': '{n} cases',
  'cart.case_count_one': '{n} case',
  'cart.change': 'Change',
  'cart.checkout_title': 'Dealer Checkout',
  'cart.deliver_to': 'Deliver to',
  'cart.empty_checkout_dealer': 'Add dealer products before checkout.',
  'cart.empty_checkout_title': 'Cart Empty',
  'cart.empty_hint': 'Add medicines, seeds or farm products to start your order.',
  'cart.empty_title': 'Your cart is empty',
  'cart.gst_note': 'GST and the final amount are confirmed on your invoice.',
  'cart.item_total': 'Item total',
  'cart.move_to_cart': 'Move to cart',
  'cart.only_cases_left': 'Only {n} cases left',
  'cart.only_one_case_left': 'Only {n} case left',
  'cart.price_details': 'Price Details',
  'cart.price_items': 'Price ({n} items)',
  'cart.proceed_to_buy': 'Proceed to Buy',
  'cart.remove_title': 'Remove from cart?',
  'cart.saved_for_later_count': 'Saved for later',
  'cart.subtotal_items': 'Subtotal ({count}): ',
  'cart.title': 'Cart',
  'cart.total': 'Total',
  'cart.total_amount': 'Total Amount',
  'cart.will_save': 'You will save {amount} on this order',

  // --- catalog -----------------------------------------------------------------
  'catalog.add_to_cart': 'Add to Cart',
  'catalog.animal_medicine': 'Animal Medicine',
  'catalog.bank_offers': 'Bank & Wallet Offers',
  'catalog.case_equals': '1 case = {n}{size}',
  'catalog.coupon_copied': 'Coupon code {code} copied',
  'catalog.default_description': 'Use this product as per label instructions and professional guidance. Keep it stored safely and away from children.',
  'catalog.default_short_description': 'Premium quality product for farm and livestock care.',
  'catalog.new_arrivals': 'New Arrivals',
  'catalog.no_products_message': 'No dealer product found in selected category.',
  'catalog.no_products_title': 'No Products',
  'catalog.per_case': '/ case',
  'catalog.product_details': 'Product Details',
  'catalog.search_hint': 'Search dealer products...',
  'catalog.search_short': 'Search dealer product',
  'catalog.shop_by_category': 'Shop By Category',
  'catalog.shop_now': 'Shop Now',
  'catalog.top_selling': 'Top Selling Items',

  // --- checkout ----------------------------------------------------------------
  'checkout.cash_upi': 'Cash / UPI Collection',
  'checkout.no_address': 'No saved address',
  'checkout.no_address_hint': 'Add an address for faster delivery.',
  'checkout.order_failed': 'Order Failed',
  'checkout.order_notes': 'Order Notes / Delivery Instructions',
  'checkout.order_submitted': 'Order Submitted',
  'checkout.order_summary': 'B2B Order Summary',
  'checkout.pay_later': 'Pay Later / Dealer Credit',
  'checkout.payment_method': 'Payment Method',
  'checkout.payment_preference': 'Payment Preference',
  'checkout.salesman_note': 'This order will be sent to your assigned salesman, then forwarded to admin for processing.',
  'checkout.sent_to_salesman': 'Dealer order has been sent to assigned salesman.',
  'checkout.submit_dealer_order': 'Submit Dealer Order {amount}',
  'checkout.submitting_order': 'Submitting Order...',

  // --- common ------------------------------------------------------------------
  'common.added': 'Added',
  'common.added_to_cart': '{name} added to cart',
  'common.address': 'Address',
  'common.bank_transfer': 'Bank Transfer',
  'common.buy_again': 'Buy again',
  'common.cancel': 'Cancel',
  'common.case_many': '{n} cases',
  'common.case_one': '{n} case',
  'common.cases_units': '{qty} · {units} units/case',
  'common.cash_on_delivery': 'Cash on Delivery',
  'common.city': 'City',
  'common.copied': 'Copied',
  'common.credit_limit': 'Credit limit',
  'common.dealer': 'Dealer',
  'common.default': 'Default',
  'common.delete': 'Delete',
  'common.description': 'Description',
  'common.email': 'Email',
  'common.in_stock': 'In stock',
  'common.invalid_server_response': 'Invalid response received from server.',
  'common.item_count_many': '{n} items',
  'common.item_count_one': '{n} item',
  'common.loading': 'Loading...',
  'common.login': 'Login',
  'common.logout_message': 'You will need to log in again to place orders.',
  'common.logout_title': 'Logout?',
  'common.message': 'Message',
  'common.months': '{n} months',
  'common.network_failed': 'Network request failed',
  'common.no_internet': 'No internet connection.',
  'common.no_items': 'No items found for this order.',
  'common.not_added': 'Not added',
  'common.notes': 'Notes',
  'common.out_of_stock': 'Out of stock',
  'common.paid': 'Paid',
  'common.payment': 'Payment',
  'common.pending': 'Pending',
  'common.products': 'Products',
  'common.qty': 'Qty {n}',
  'common.remove': 'Remove',
  'common.request_failed': 'Request failed',
  'common.required': 'Required',
  'common.retry': 'Try Again',
  'common.save_for_later': 'Save for later',
  'common.saving': 'Saving...',
  'common.see_all': 'See All',
  'common.sending': 'Sending...',
  'common.something_wrong': 'Something went wrong. Please try again.',
  'common.submitting': 'Submitting...',
  'common.view': 'View',
  'common.view_all': 'View All',

  // --- home --------------------------------------------------------------------
  'home.copy': 'Copy',
  'home.credit_limit': 'Credit Limit',
  'home.hero_subtitle': 'B2B Products at Dealer Prices',
  'home.hero_title': 'Dealer Price Store',
  'home.load_failed': 'Unable to load dealer products',
  'home.outstanding': 'Outstanding',
  'home.pending': 'Pending',
  'home.start_order': 'Start Order',

  // --- invoice -----------------------------------------------------------------
  'invoice.amount_details': 'Amount details',
  'invoice.could_not_download': 'Could not download the invoice.',
  'invoice.discount': 'Discount',
  'invoice.download': 'Download PDF',
  'invoice.download_failed': 'Download failed',
  'invoice.empty_message': 'An invoice appears here once your order is billed.',
  'invoice.empty_title': 'No invoices yet',
  'invoice.grand_total': 'Grand total',
  'invoice.gst': 'GST',
  'invoice.invoice_date': 'Invoice date',
  'invoice.items': 'Items',
  'invoice.no_match_message': 'Try a different invoice or order number.',
  'invoice.no_match_title': 'No matching invoice',
  'invoice.no_viewer': 'Saved to your device, but no PDF viewer is installed to open it.',
  'invoice.not_found': 'Invoice not found.',
  'invoice.preparing': 'Preparing PDF...',
  'invoice.saved': 'Invoice saved',
  'invoice.saved_as': 'Saved as',
  'invoice.search_hint': 'Search invoice or order number',
  'invoice.subtotal': 'Subtotal',
  'invoice.title': 'Invoice',
  'invoice.total_amount': 'Total amount',
  'invoice.unavailable': 'Invoice unavailable',
  'invoice.view': 'View Invoice',

  // --- language ----------------------------------------------------------------
  'language.subtitle': 'Product names and app text will be shown in this language.',
  'language.title': 'Choose your language',
  'language.updating': 'Applying language...',

  // --- menu --------------------------------------------------------------------
  'menu.account': 'Account',
  'menu.change_password': 'Change Password',
  'menu.edit_profile': 'Edit Profile',
  'menu.invoices': 'Invoices',
  'menu.language': 'Language',
  'menu.logout': 'Logout',
  'menu.notifications': 'Notifications',
  'menu.order_history': 'Order History',
  'menu.outstanding': 'Outstanding & Credit',
  'menu.payments': 'Payments',
  'menu.reports': 'Reports',
  'menu.returns': 'Returns',
  'menu.support': 'Support',

  // --- nav ---------------------------------------------------------------------
  'nav.cart': 'Cart',
  'nav.category': 'Category',
  'nav.home': 'Home',
  'nav.menu': 'Menu',
  'nav.orders': 'Orders',

  // --- notifications -----------------------------------------------------------
  'notifications.empty_message': 'Order approvals, dispatches and notices show up here.',
  'notifications.empty_title': 'No notifications',
  'notifications.mark_all_read': 'Mark all read',
  'notifications.title': 'Notifications',

  // --- orders ------------------------------------------------------------------
  'orders.add_to_cart': 'Add to cart',
  'orders.added_from_order': '{n} product(s) from {order}',
  'orders.added_to_cart_title': 'Added to cart',
  'orders.all': 'All',
  'orders.all_time': 'All time',
  'orders.approved': 'Approved',
  'orders.arriving_soon': 'Arriving soon',
  'orders.being_packed': 'Being packed',
  'orders.buy_again': 'Buy Again',
  'orders.buy_again_message': 'Products from your orders will appear here.',
  'orders.cancel_not_reversible': 'This cannot be undone. Please tell us why you are cancelling.',
  'orders.cancel_order': 'Cancel Order',
  'orders.cancellation_reason': 'Reason for cancelling',
  'orders.cancelled': 'Cancelled',
  'orders.confirmed': 'Order confirmed',
  'orders.current': 'Current Orders',
  'orders.delivered': 'Delivered',
  'orders.delivered_on': 'Delivered {date}',
  'orders.details': 'Details',
  'orders.dispatched': 'Dispatched',
  'orders.empty_message': 'Try a different search, tab or time period.',
  'orders.in_review': 'In Review',
  'orders.invoice': 'Invoice',
  'orders.last_30_days': 'Last 30 days',
  'orders.last_3_months': 'Last 3 months',
  'orders.no_current_message': 'Orders you place stay here until they are delivered.',
  'orders.no_current_title': 'No Current Orders',
  'orders.no_match_title': 'No matching orders',
  'orders.no_past_message': 'Delivered and cancelled orders will appear here.',
  'orders.no_past_title': 'No Past Orders',
  'orders.nothing_to_buy_again': 'Nothing to buy again',
  'orders.on_the_way': 'On the way',
  'orders.order_cancelled': 'Order Cancelled',
  'orders.order_cancelled_message': '{order} has been cancelled.',
  'orders.order_items': 'Order items',
  'orders.out_for_delivery': 'Out for Delivery',
  'orders.out_for_delivery_short': 'Out for delivery',
  'orders.packing': 'Packing',
  'orders.return': 'Return',
  'orders.return_received': 'We received your return request for {order}.',
  'orders.return_requested': 'Return requested',
  'orders.return_title': 'Return',
  'orders.search_hint': 'Search current orders',
  'orders.search_history_hint': 'Search past orders or products',
  'orders.tell_why_cancelling': 'Please tell us why you are cancelling.',
  'orders.this_year': 'This year',
  'orders.time_period': 'Time period',
  'orders.track_short': 'Track',
  'orders.tracking_history': 'Tracking History',
  'orders.unavailable_products': 'These products are no longer available.',
  'orders.under_review': 'Under Review',

  // --- outstanding -------------------------------------------------------------
  'outstanding.last_payment': 'Last payment',
  'outstanding.ledger': 'Ledger',
  'outstanding.load_failed': 'We could not load your credit position.',
  'outstanding.no_ledger': 'No ledger entries yet.',
  'outstanding.over_limit': 'You are over your credit limit. Clear dues to place new orders.',
  'outstanding.still_available': '{amount} still available',
  'outstanding.unavailable': 'Account unavailable',
  'outstanding.unpaid_orders': 'Unpaid orders',

  // --- password ----------------------------------------------------------------
  'password.at_least': 'At least {n} characters.',
  'password.change_failed': 'Change Failed',
  'password.changed': 'Password Changed',
  'password.changed_message': 'Use your new password next time you log in.',
  'password.enter_current': 'Enter your current password.',
  'password.intro_existing': 'Enter your current password, then choose a new one.',
  'password.intro_otp': 'You sign in with mobile OTP, so no current password is needed. Choose a password for your account.',
  'password.min_length': 'New password must be at least {n} characters.',
  'password.no_match': 'Does not match',
  'password.no_match_message': 'New password and confirm password must be the same.',
  'password.too_short': 'Too short',
  'password.update': 'Update Password',

  // --- payments ----------------------------------------------------------------
  'payments.empty_message': 'Payments you make against invoices will appear here.',
  'payments.empty_title': 'No payments yet',

  // --- profile -----------------------------------------------------------------
  'profile.choose_gallery': 'Choose from Gallery',
  'profile.edit': 'Edit profile',
  'profile.enter_name_firm': 'Enter your name and firm name.',
  'profile.mobile_locked': 'Mobile number cannot be changed.',
  'profile.photo_updated': 'Photo Updated',
  'profile.photo_updated_message': 'Your profile photo has been changed.',
  'profile.save_changes': 'Save Changes',
  'profile.take_photo': 'Take Photo',
  'profile.update_failed': 'Update Failed',
  'profile.updated': 'Profile Updated',
  'profile.updated_message': 'Your profile details have been saved.',
  'profile.upload_failed': 'Upload Failed',

  // --- reports -----------------------------------------------------------------
  'reports.by_month': 'By month',
  'reports.by_status': 'By status',
  'reports.load_failed': 'We could not build your purchase report.',
  'reports.no_purchases': 'No purchases in this window.',
  'reports.orders_placed': 'Orders placed',
  'reports.purchase_value': 'Purchase value',
  'reports.top_products': 'Top products',
  'reports.unavailable': 'Report unavailable',

  // --- returns -----------------------------------------------------------------
  'returns.empty_message': 'Raise a return from any delivered order within 7 days.',
  'returns.empty_title': 'No returns',
  'returns.order_no': 'Order {order}',
  'returns.reason': 'Reason for return',
  'returns.submit': 'Submit Return Request',
  'returns.submitted': 'Your return request has been submitted.',
  'returns.tell_why': 'Tell us why you are returning this order.',
  'returns.window': 'Returns are accepted within {n} days of delivery.',

  // --- shell -------------------------------------------------------------------
  'shell.categories': 'Categories',
  'shell.dealer_store': 'Dealer Store',
  'shell.welcome': 'Welcome, {name}',

  // --- support -----------------------------------------------------------------
  'support.create_ticket': 'Create Ticket',
  'support.enter_subject_message': 'Enter subject and message.',
  'support.failed': 'Support Failed',
  'support.need_help': 'Need Help',
  'support.sent': 'Support Sent',
  'support.sent_message': 'Your support ticket has been created.',
  'support.subject': 'Subject',

  // --- tracking ----------------------------------------------------------------
  'tracking.cancelled_note': 'This order was cancelled. Contact support for help with a replacement or refund.',
  'tracking.code': 'Tracking Code',
  'tracking.courier': 'Courier',
  'tracking.deliver_to': 'Deliver To',
  'tracking.destination': 'Destination',
  'tracking.from': 'From',
  'tracking.items': 'Items',
  'tracking.last_update': 'Last Update',
  'tracking.link_copied': 'Courier tracking link copied',
  'tracking.loading': 'Fetching order status...',
  'tracking.no_order': 'No order selected.',
  'tracking.no_updates': 'No tracking updates yet.',
  'tracking.no_updates_short': 'No updates yet.',
  'tracking.not_found': 'We could not find tracking details for this order.',
  'tracking.order': 'Order',
  'tracking.order_received': 'Order received',
  'tracking.package': 'Package',
  'tracking.package_summary': '{n} item(s) · {amount}',
  'tracking.payment_status': 'Payment Status',
  'tracking.placed_on': 'Placed on',
  'tracking.progress': 'Order Progress',
  'tracking.review_desk': 'Order review desk',
  'tracking.tap_copy': 'Tap to copy tracking link',
  'tracking.title': 'Track Order',
  'tracking.unavailable': 'Cannot track this order',
  'tracking.with_partner': 'With delivery partner, on the way to you',
  // --- location ----------------------------------------------------------------
  'location.city_village': 'City / Village',
  'location.district': 'District',
  'location.enter_city': 'Please enter city or village',
  'location.enter_taluka': 'Please type the taluka name',
  'location.invalid_pincode': 'Pincode must be 6 digits',
  'location.load_failed': 'Could not load locations. Check your internet and try again.',
  'location.other_taluka': 'Other (type taluka)',
  'location.pincode': 'Pincode',
  'location.select_district': 'Please select district',
  'location.select_state': 'Please select state',
  'location.select_taluka': 'Please select taluka',
  'location.state': 'State',
  'location.taluka': 'Sub-district / Taluka',
  'location.taluka_name': 'Taluka name',
  'location.title': 'Location',
};
